In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("qoute_dataset.csv")

In [ ]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [ ]:
df.shape

(3038, 2)

In [ ]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
quotes = quotes.str.lower()
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices, harry, that show what we t...
2    “there are only two ways to live your life. on...
3    “the person, be it gentleman or lady, who has ...
4    “imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
import string
translator = str.maketrans('', '', string.punctuation)
quotes = quotes.str.translate(translator)
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
vocab_size = 8978

tokenizer = Tokenizer(num_words=vocab_size, oov_token='<OOV>')
tokenizer.fit_on_texts(quotes)
word_index = tokenizer.word_index

In [ ]:
print(len(word_index))
print(list(word_index.items())[:10])

8979
[('<OOV>', 1), ('the', 2), ('you', 3), ('to', 4), ('and', 5), ('a', 6), ('i', 7), ('is', 8), ('of', 9), ('that', 10)]

In [ ]:
sequence = tokenizer.texts_to_sequences(quotes)

In [ ]:
quotes[0]

'“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”'

In [ ]:
sequence[0]

[714,
 63,
 30,
 20,
 17,
 947,
 11,
 8,
 6,
 1157,
 9,
 71,
 294,
 11,
 146,
 13,
 810,
 105,
 753,
 71,
 2462]

In [ ]:
X = []
y = []

for seq in sequence:
  for i in range(1, len(seq)):
    input_seq = seq[:i]
    output_seq = seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [ ]:
len(X)

85271

In [ ]:
len(y)

85271

In [ ]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

In [ ]:
y = np.array(y)

In [ ]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y, num_classes=vocab_size)

In [ ]:
y.shape

(85271,)

In [ ]:
y_one_hot.shape

(85271, 8978)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN,LSTM, Dense, Dropout

In [ ]:
embedding_dim = 50
rnn_units = 128

## RNN

In [ ]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
    )
rnn_model.add(
    SimpleRNN(units=rnn_units)
    )
rnn_model.add(
    Dense(units=vocab_size, activation='softmax')
    )

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

## LSTM

In [ ]:
lstm_model = Sequential()

lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_len)
)
lstm_model.add(
    LSTM(units=rnn_units)
)
lstm_model.add(
    Dense(units=vocab_size, activation='softmax')
)

In [ ]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# epochs = 70
# batch_size = 128
# history_rnn = rnn_model.fit(
#     X_padded, y_one_hot,
#     epochs=epochs,
#     batch_size=batch_size,
#     validation_split=0.1
# )

In [ ]:
epochs = 90  # You can adjust this value
batch_size = 128 # You can adjust this value

Now, let's train the LSTM model with the defined parameters and early stopping.

In [ ]:
history_lstm = lstm_model.fit(
    X_padded, y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.1 # Use 10% of the data for validation

)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.1180 - loss: 5.4663 - val_accuracy: 0.1052 - val_loss: 6.4774
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1263 - loss: 5.2996 - val_accuracy: 0.1083 - val_loss: 6.5348
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1329 - loss: 5.1520 - val_accuracy: 0.1093 - val_loss: 6.5889
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1394 - loss: 5.0123 - val_accuracy: 0.1127 - val_loss: 6.6462
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1469 - loss: 4.8778 - val_accuracy: 0.1141 - val_loss: 6.7235
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.1549 - loss: 4.7463 - val_accuracy: 0.1152 - val_loss: 6.7911
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1635 - loss: 4.6213 - val_accuracy: 0.1159 - val_loss: 6.8643
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1723 - loss: 4.4970 - val_accuracy: 0.1164 - val_loss: 6.9335
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1830 - loss: 4.3788 - val_accuracy: 0.1150 - val_loss: 7.0008
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1955 - loss: 4.2657 - val_accuracy: 0.1142 - val_loss: 7.0905
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2069 - loss: 4.1577 - val_accuracy: 0.1167 - val_loss: 7.1526
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.2205 - loss: 4.0540 - val_accuracy: 0.1139 - val_loss: 7.2324
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.2350 - loss: 3.9572 - val_accuracy: 0.1140 - val_loss: 7.3019
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2470 - loss: 3.8649 - val_accuracy: 0.1137 - val_loss: 7.3776
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2584 - loss: 3.7790 - val_accuracy: 0.1114 - val_loss: 7.4521
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2718 - loss: 3.6985 - val_accuracy: 0.1120 - val_loss: 7.5339
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.2841 - loss: 3.6210 - val_accuracy: 0.1101 - val_loss: 7.5850
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2947 - loss: 3.5502 - val_accuracy: 0.1086 - val_loss: 7.6556
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3043 - loss: 3.4797 - val_accuracy: 0.1071 - val_loss: 7.7197
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3149 - loss: 3.4134 - val_accuracy: 0.1093 - val_loss: 7.7936
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3256 - loss: 3.3500 - val_accuracy: 0.1074 - val_loss: 7.8557
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3354 - loss: 3.2869 - val_accuracy: 0.1073 - val_loss: 7.9252
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 54ms/step - accuracy: 0.3453 - loss: 3.2281 - val_accuracy: 0.1054 - val_loss: 7.9983
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3552 - loss: 3.1705 - val_accuracy: 0.1073 - val_loss: 8.0486
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3624 - loss: 3.1154 - val_accuracy: 0.1049 - val_loss: 8.1114
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3725 - loss: 3.0613 - val_accuracy: 0.1038 - val_loss: 8.1784
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.3813 - loss: 3.0078 - val_accuracy: 0.1019 - val_loss: 8.2394
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3902 - loss: 2.9571 - val_accuracy: 0.1018 - val_loss: 8.2936
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3990 - loss: 2.9093 - val_accuracy: 0.1006 - val_loss: 8.3458
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4074 - loss: 2.8606 - val_accuracy: 0.1015 - val_loss: 8.3999
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4138 - loss: 2.8140 - val_accuracy: 0.1001 - val_loss: 8.4613
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4227 - loss: 2.7690 - val_accuracy: 0.0997 - val_loss: 8.5256
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4296 - loss: 2.7251 - val_accuracy: 0.0979 - val_loss: 8.5806
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4380 - loss: 2.6815 - val_accuracy: 0.0976 - val_loss: 8.6531
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4460 - loss: 2.6395 - val_accuracy: 0.0966 - val_loss: 8.6926
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4535 - loss: 2.5993 - val_accuracy: 0.0964 - val_loss: 8.7553
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4599 - loss: 2.5591 - val_accuracy: 0.0976 - val_loss: 8.8201
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 54ms/step - accuracy: 0.4678 - loss: 2.5209 - val_accuracy: 0.0950 - val_loss: 8.8827
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4750 - loss: 2.4831 - val_accuracy: 0.0949 - val_loss: 8.9217
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4801 - loss: 2.4455 - val_accuracy: 0.0990 - val_loss: 8.9831
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4884 - loss: 2.4102 - val_accuracy: 0.0945 - val_loss: 9.0369
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.4959 - loss: 2.3750 - val_accuracy: 0.0936 - val_loss: 9.0919
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.5018 - loss: 2.3401 - val_accuracy: 0.0912 - val_loss: 9.1386
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5086 - loss: 2.3073 - val_accuracy: 0.0913 - val_loss: 9.2053
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5140 - loss: 2.2750 - val_accuracy: 0.0951 - val_loss: 9.2788
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5195 - loss: 2.2414 - val_accuracy: 0.0909 - val_loss: 9.3158
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5260 - loss: 2.2105 - val_accuracy: 0.0904 - val_loss: 9.3697
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.5319 - loss: 2.1805 - val_accuracy: 0.0909 - val_loss: 9.4241
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5376 - loss: 2.1498 - val_accuracy: 0.0894 - val_loss: 9.4873
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5438 - loss: 2.1212 - val_accuracy: 0.0885 - val_loss: 9.5272
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5489 - loss: 2.0921 - val_accuracy: 0.0875 - val_loss: 9.5999
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5543 - loss: 2.0639 - val_accuracy: 0.0862 - val_loss: 9.6463
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5604 - loss: 2.0362 - val_accuracy: 0.0868 - val_loss: 9.7146
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5643 - loss: 2.0101 - val_accuracy: 0.0862 - val_loss: 9.7666
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5696 - loss: 1.9842 - val_accuracy: 0.0882 - val_loss: 9.8246
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5743 - loss: 1.9589 - val_accuracy: 0.0867 - val_loss: 9.8561
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5810 - loss: 1.9333 - val_accuracy: 0.0849 - val_loss: 9.9175
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5856 - loss: 1.9103 - val_accuracy: 0.0844 - val_loss: 9.9562
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5899 - loss: 1.8861 - val_accuracy: 0.0842 - val_loss: 10.0155
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 54ms/step - accuracy: 0.5937 - loss: 1.8622 - val_accuracy: 0.0804 - val_loss: 10.0644
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5993 - loss: 1.8374 - val_accuracy: 0.0840 - val_loss: 10.1199
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6042 - loss: 1.8170 - val_accuracy: 0.0811 - val_loss: 10.1690
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6082 - loss: 1.7934 - val_accuracy: 0.0830 - val_loss: 10.2189
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6126 - loss: 1.7730 - val_accuracy: 0.0818 - val_loss: 10.2616
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6164 - loss: 1.7503 - val_accuracy: 0.0816 - val_loss: 10.3153
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6210 - loss: 1.7297 - val_accuracy: 0.0841 - val_loss: 10.3450
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6254 - loss: 1.7092 - val_accuracy: 0.0823 - val_loss: 10.4290
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6233 - loss: 1.7102 - val_accuracy: 0.0807 - val_loss: 10.4289
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6255 - loss: 1.7035 - val_accuracy: 0.0795 - val_loss: 10.4911
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 54ms/step - accuracy: 0.6341 - loss: 1.6700 - val_accuracy: 0.0823 - val_loss: 10.5211
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6370 - loss: 1.6480 - val_accuracy: 0.0811 - val_loss: 10.5633
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6422 - loss: 1.6301 - val_accuracy: 0.0799 - val_loss: 10.6147
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.6459 - loss: 1.6100 - val_accuracy: 0.0820 - val_loss: 10.6571
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 40s 54ms/step - accuracy: 0.6491 - loss: 1.5935 - val_accuracy: 0.0804 - val_loss: 10.7221
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6540 - loss: 1.5751 - val_accuracy: 0.0811 - val_loss: 10.7591
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6566 - loss: 1.5567 - val_accuracy: 0.0799 - val_loss: 10.7988
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6613 - loss: 1.5389 - val_accuracy: 0.0784 - val_loss: 10.8549
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6647 - loss: 1.5226 - val_accuracy: 0.0797 - val_loss: 10.9061
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6685 - loss: 1.5058 - val_accuracy: 0.0789 - val_loss: 10.9376
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6719 - loss: 1.4904 - val_accuracy: 0.0781 - val_loss: 10.9955
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6756 - loss: 1.4740 - val_accuracy: 0.0793 - val_loss: 11.0505
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6786 - loss: 1.4572 - val_accuracy: 0.0775 - val_loss: 11.0900
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6823 - loss: 1.4424 - val_accuracy: 0.0769 - val_loss: 11.1324
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6846 - loss: 1.4265 - val_accuracy: 0.0766 - val_loss: 11.1683
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6882 - loss: 1.4120 - val_accuracy: 0.0787 - val_loss: 11.2277
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6917 - loss: 1.3959 - val_accuracy: 0.0756 - val_loss: 11.2691
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6953 - loss: 1.3831 - val_accuracy: 0.0788 - val_loss: 11.3032
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6970 - loss: 1.3691 - val_accuracy: 0.0789 - val_loss: 11.3728
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7017 - loss: 1.3538 - val_accuracy: 0.0753 - val_loss: 11.4097
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7041 - loss: 1.3404 - val_accuracy: 0.0780 - val_loss: 11.4482
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7064 - loss: 1.3281 - val_accuracy: 0.0787 - val_loss: 11.5039
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.7097 - loss: 1.3134 - val_accuracy: 0.0783 - val_loss: 11.5233
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7131 - loss: 1.3016 - val_accuracy: 0.0763 - val_loss: 11.5906
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7155 - loss: 1.2877 - val_accuracy: 0.0765 - val_loss: 11.6340
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7176 - loss: 1.2753 - val_accuracy: 0.0746 - val_loss: 11.6798
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7201 - loss: 1.2637 - val_accuracy: 0.0727 - val_loss: 11.7296
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7236 - loss: 1.2517 - val_accuracy: 0.0754 - val_loss: 11.7760
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7271 - loss: 1.2375 - val_accuracy: 0.0745 - val_loss: 11.8108
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7287 - loss: 1.2264 - val_accuracy: 0.0727 - val_loss: 11.8492
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7314 - loss: 1.2161 - val_accuracy: 0.0772 - val_loss: 11.8958

In [ ]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
index_to_word = {}
for word, index in word_index.items():
  index_to_word[index] = word

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])[0]
  seq = pad_sequences([seq], maxlen=max_len, padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_index = np.argmax(pred)
  return index_to_word[pred_index]

In [ ]:
seed_text = "hello guys"
next_word = predictor(lstm_model,tokenizer,seed_text,max_len)
print(next_word)

are

In [ ]:
def generate_text(model,tokenizer,seed_text,max_len,n_words):
  for _ in range(n_words):
    next_word = predictor(model,tokenizer,seed_text,max_len)
    if next_word == "":
      break
    seed_text += " " + next_word
  return seed_text

In [ ]:

seed = "are you a "
generate_text = generate_text(lstm_model,tokenizer,seed,max_len,10)
print(generate_text)

are you a  thousand times is in trying to put the things that

In [ ]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokenizer, f)

In [ ]:
with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)